### ISSUE TITLE
Reasoning for using .NET Stnd 2.1?

### ISSUE THREAD

**Issue by jasells** [MatejFranceskin/GeoidHeightsDotNet#4]
So, I really need to use your package, but since it is built as v 2.1, I can't import it to my project because all of my stuff is 2.0.

Looking at the code, there is nothing requiring > 1.6 for sure, and could probably go as low as 1.2, as currently written and avoid these kind of compatibility issues.

Just wondering if you ran into something that forced you to upgrade it?

Update: I didn't see the older version, which should work for me right now... but still wondering if you had a specific reason for going to 2.1?

**Comment by MatejFranceskin** [comment]
I think it was upgraded by @janusw in this PR: https://github.com/MatejFranceskin/GeoidHeightsDotNet/pull/2

**Comment by MatejFranceskin** [comment]
So I guess you solved your problem by using an older version, right?

**Comment by janusw** [comment]
> Looking at the code, there is nothing requiring > 1.6 for sure, and could probably go as low as 1.2, as currently written and avoid these kind of compatibility issues.
> 
> Just wondering if you ran into something that forced you to upgrade it?

Actually I did not try any older framework versions. My primary intention was to port the library to .NET Standard, so that I can use it in a Xamarin cross-platform project. I had no necessity for supporting older framework versions, so I just used the latest one.

Might well be that the code is compatible with older versions of .NET Standard. You could just try it and open a pull request if it works.

**Comment by jasells** [comment]
Yes, the older package can be used by Standard 2.0 libs, at least.  It gives a warning, but works just fine since this lib is only doing basic math, no unsupported API's are called.  I looked @ the history and saw that PR and that the only change was in the config, no code changes.

I may issue a PR when I get some time.  This code doesn't require anything above 1.2, but 1.6 is probably wide enough to support anyone trying to use it.


FYI, I'm using this in Xamarin too, so it wasn't strictly required to upgrade it at to Stnd at all to use it, depending on what version the consuming projects are.

**Comment by jasells** [comment]
This is a good summary of how to pick the .NET stnd version to use in a lib.
https://docs.microsoft.com/en-us/dotnet/standard/net-standard

My rule of thumb for Xamarin is to make the app projects as high (new) as possible, including the Forms project, and all other libs are as low as possible for widest re-use.

**Comment by jasells** [comment]
PR https://github.com/MatejFranceskin/GeoidHeightsDotNet/pull/5

**Comment by MatejFranceskin** [comment]
Thank you very much - I merged it!

**Comment by jasells** [comment]
Can you package and push the v1.1 package to nuget?  

Mondroid 8.1 will build in debug and release locally, but fails when trying to build .apk  against the latest v1.0.2 package.
