### ISSUE TITLE
Request for a package release of the .Net Stnd 1.1 build

### ISSUE THREAD

**Issue by jasells** [MatejFranceskin/GeoidHeightsDotNet#6]
So, I am able to build my projects in debug with the old DNFW 4.6/4.7 package, but I am stuck in a nether-region where my Android projects can't build package with the old version, and don't support the newer version.

If you could just release a new package based off the changes you merged, I won't have to fork and create a variant package, we can all use this same code base!

Thanks!

**Comment by janusw** [comment]
@MatejFranceskin I second the request of @jasells. A new release (1.0.3?) with support for .NET Standard 1.1 would be very useful. In particular this is necessary for targeting UWP, which only supports .NET Standard up to 2.0 right now, but not 2.1 (which is required by GeoidHeightsDotNet 1.0.2).

**Comment by jasells** [comment]
@MatejFranceskin 
I also have issues with UWP... currently I am building and packaging a local fork.  I may publish that fork, if there is no response.  Been waiting +3 months....

I really don't want to fork it, or especially publish a package of that fork.  I'd hate to create potential confusion, but I have to do something to avoid internal issues with my dependent project.

**Comment by janusw** [comment]
> I also have issues with UWP... currently I am building and packaging a local fork. I may publish that fork, if there is no response. Been waiting +3 months....
> 
> I really don't want to fork it, or especially publish a package of that fork. I'd hate to create potential confusion, but I have to do something to avoid internal issues with my dependent project.

I'm absolutely with you here, @jasells. I also feel like forking is not the best solution, but if there is no response it cannot be avoided.

@MatejFranceskin Do you have any intention to keep on maintaining this project at all, or have you abandoned it completely?

As an alternative suggestion to forking: Maybe we could share the maintenance burden? I.e. create a new organization (named "GeoidHeightsDotNet"?), move the repository there and put in the three of us as maintainers. How does that sound to you?

**Comment by jasells** [comment]
> > I also have issues with UWP... currently I am building and packaging a local fork. I may publish that fork, if there is no response. Been waiting +3 months....
> > I really don't want to fork it, or especially publish a package of that fork. I'd hate to create potential confusion, but I have to do something to avoid internal issues with my dependent project.
> 
> I'm absolutely with you here, @jasells. I also feel like forking is not the best solution, but if there is no response it cannot be avoided.
> 
> @MatejFranceskin Do you have any intention to keep on maintaining this project at all, or have you abandoned it completely?
> 
> As an alternative suggestion to forking: Maybe we could share the maintenance burden? I.e. create a new organization (named "GeoidHeightsDotNet"?), move the repository there and put in the three of us as maintainers. How does that sound to you?

I'd be game for that.  I was even testing an Azure pipeline to do the build this afternoon.  It was surprisingly easy to set it up to build from a github repo.

If we're going to set up a new org, it might be worth considering setting it up in Azure Devops, just to make a single place instead of split between Github and a second system for the build/publish back end?  Just a thought?  It would still be open and free.

I am familiar with the ArduPilot project that is the original consumer for this package.  I expect long quiet spells on this since it is probably working as needed for them.  They aren't expecting much other interest.  I was actually surprised by the quick response on my original PR to update it to .NEt Stnd 1.1.  If they had an automated build system set up, this wouldn't be an issue, as the PR completion would have published the update.

I have auto-versioning set up for my private packages that would have auto-published the update if set up here.

Short of the new org, I was just forking it [here](https://github.com/jasells/GeoidHeightsDotNet/tree/DnStnd1.1-Packaging) in hopes it was temporary.  I haven't published the package yet, just testing the pipeline, and feeling out how much change is actually needed to publish a package from the fork that doesn't clash, but is still traceable to the original version.

**Comment by janusw** [comment]
> > As an alternative suggestion to forking: Maybe we could share the maintenance burden? I.e. create a new organization (named "GeoidHeightsDotNet"?), move the repository there and put in the three of us as maintainers. How does that sound to you?
> 
> I'd be game for that. I was even testing an Azure pipeline to do the build this afternoon. It was surprisingly easy to set it up to build from a github repo.

Alright then. I have created the org and invited both of you.

I still hope that @MatejFranceskin might be willing to support this effort, so IMHO we should give him time until the weekend to react. If he is willing to join, we should move his original project into the new org. If not, I will move my fork there on Sunday.

> If we're going to set up a new org, it might be worth considering setting it up in Azure Devops, just to make a single place instead of split between Github and a second system for the build/publish back end? Just a thought? It would still be open and free.

Yes, I also had that in mind. Definitely something we should do. But let's just wait a few more days for a reply, before we go ahead with further actions.

@MatejFranceskin Please give us some sign of life here. If you are not interested in maintaining this project any more, it would be useful to express that, so that we can take over. If you are, all the better :)

**Comment by janusw** [comment]
> I still hope that @MatejFranceskin might be willing to support this effort, so IMHO we should give him time until the weekend to react. If he is willing to join, we should move his original project into the new org. If not, I will move my fork there on Sunday.

It seems like @MatejFranceskin has joined the new org (thanks for that!). So, if you agree to this plan, I suggest you should move the GeoidHeightsDotNet project into the new GeoidHeightsDotNet org, @MatejFranceskin.

To do that, you should go to https://github.com/MatejFranceskin/GeoidHeightsDotNet/settings, scroll down to the "Danger Zone" and click the "transfer" button, to transfer the repository to the GeoidHeightsDotNet org, where we can continue maintaining it as a team. If any problems arise, please let me know!

Thanks a lot for your collaboration!

**Comment by MatejFranceskin** [comment]
Sorry for not replying before - I completely missed this. Which is a good reason for transferring the repository to the org.
Thanks for your patience!

**Comment by MatejFranceskin** [comment]
Nice logo BTW. :-)

**Comment by janusw** [comment]
Alright, seems you have managed to transfer the repo. Excellent! Thanks a bunch ...

**Comment by janusw** [comment]
@jasells Have you been looking into any CI/CD pipeline yet?

I thought we could use Github Actions for generating nuget packages, see https://docs.github.com/en/actions/guides/building-and-testing-net.

**Comment by jasells** [comment]
> @jasells Have you been looking into any CI/CD pipeline yet?
> 
> I thought we could use Github Actions for generating nuget packages, see https://docs.github.com/en/actions/guides/building-and-testing-net.

True, I just saw that yesterday.  I am familiar with DevOps, not so much with the back end of GitHub.

re: Have you been looking into any CI/CD pipeline?

Yes, I have a DevOps pipeline already connected to my fork and test built the repo.

**Comment by janusw** [comment]
> re: Have you been looking into any CI/CD pipeline?
> 
> Yes, I have a DevOps pipeline already connected to my fork and test built the repo.

Ok, so you're using Azure there apparently. However, I cannot access those builds. I'd actually prefer to use Github Actions if possible, so that we really have everything in one place. Or do you see any major advantage in using Azure?

Maybe for now I'll start by tagging a release 1.0.3 and building the package manually. We can still figure out a CI/CD solution afterwards ...

**Comment by janusw** [comment]
Alright, version 1.0.3 (based on .NET Standard 1.1) has been built, tagged and uploaded to nuget.org.

Thus, I'm closing this issue 🎉
