### ISSUE TITLE
Setting up CI build hooks

### ISSUE THREAD

**Issue by janusw** [MatejFranceskin/GeoidHeightsDotNet#8]
This is a follow-up to the discussion started in #6 and #7: GeoidHeightsDotNet should have CI build hooks for automatic building, testing and packaging. The following options have been proposed so far:
* Azure DevOps pipeline
* Github Actions

I might look into the second one soon, unless @jasells beats me to it by implementing the first :wink:

**Comment by jasells** [comment]
If you get it set up here, it's fine with me, I just don't have the day or two it looks like it will take me to learn the way GitActions does it.

I was hoping we would just move the whole project over to Azure DevOps to avoid the split, but I guess a question we should ask now that we have v1.0.3 package published is: do we really need to worry about CI? What else might change?

I don't see a high likelihood of any other updates, and until we do, maybe we just defer any CI until then?

If we really want CI, and you don't think you'll get to it soon with GitActions, I'll go ahead and set up a mirror org on DevOps and the pipeline there. It really won't take me long there, just because that's where I work daily.

Just let me know if that's the desired route.

**Comment by janusw** [comment]
> I was hoping we would just move the whole project over to Azure DevOps to avoid the split

You mean, moving the repository to Azure? I don't see much of a reason for doing that. Does Azure even support public repos?

> but I guess a question we should ask now that we have v1.0.3 package published is: do we really need to worry about CI? What else might change?

Well, predictions are always difficult. In particular if they concern the future ;)

Do we need CI? Not necessarily. Is it a nice-to-have? Certainly. I had the impression you were the one who suggested it :)
 
> If we really want CI, and you don't think you'll get to it soon with GitActions, I'll go ahead and set up a mirror org on DevOps and the pipeline there. It really won't take me long there, just because that's where I work daily.

I don't think it should be very hard to set up Github Actions, and I don't plan to put too much work into it.

Maybe you can just give me a few days to find some time for it. If I don't manage to get there by next weekend, feel free to set up the Azure pipeline ...

**Comment by janusw** [comment]
Alright, I have played a bit with GitHub Actions in my fork and found a config that is reasonable from my point of view (see #10). Feedback welcome.

The CI config will not be active here before the branch is merged. However, you can see some example builds on the master branch in my fork. The last commit there corresponds to the state that I have squashed into #10.

**Comment by janusw** [comment]
Fixed via #10. Closing.

**Comment by janusw** [comment]
In case it's not obvious to everyone, I should mention the effects of PR #10:
* Every commit to master and every pull request will be built and tested automatically from now on (via the GitHub Actions CI system).
* Github's revision history will show a small icon for each revision, indicating the result of the CI build. It can be clicked to see further details.
* The details include the full log for every step of the CI build and the nupkg built from the corresponding revision as an artifact.

Here is an example: https://github.com/GeoidHeightsDotNet/GeoidHeightsDotNet/runs/2191425749

**Comment by jasells** [comment]
@janusw 
>You mean, moving the repository to Azure? I don't see much of a reason for doing that. Does Azure even support public repos?

Yes, Azure DevOps has public repos.  I have several, here's one of mine: https://xdevapps.visualstudio.com/MavLink.Net

That was just what I was thinking since I knew how to set that up.

**Comment by janusw** [comment]
> > You mean, moving the repository to Azure? I don't see much of a reason for doing that. Does Azure even support public repos?
> 
> Yes, Azure DevOps has public repos. I have several, here's one of mine: https://xdevapps.visualstudio.com/MavLink.Net

Interesting, didn't know that.

Honestly though, I think GitHub is simply doing too many things right. I really don't see a single reason for moving away from it.

**Comment by jasells** [comment]
> > > You mean, moving the repository to Azure? I don't see much of a reason for doing that. Does Azure even support public repos?
> > 
> > 
> > Yes, Azure DevOps has public repos. I have several, here's one of mine: https://xdevapps.visualstudio.com/MavLink.Net
> 
> Interesting, didn't know that.
> 
> Honestly though, I think GitHub is simply doing too many things right. I really don't see a single reason for moving away from it.

*If* this were an active repo, I think the main advantage would be more robust issue/workitem tracking.  DevOps has a much nicer agile/scrum backlog system that makes tracking which issues/items should be worked first and are currently being worked easier to see than the single issue list in GitHub and makes it easier for team efforts.
GitHub seems pretty single-dev oriented, with collaboration and dividing up issues left to coordinate amongst the users... some way not integrated here, except for messages left in the issue threads.

**Comment by janusw** [comment]
> > Honestly though, I think GitHub is simply doing too many things right. I really don't see a single reason for moving away from it.
> 
> _If_ this were an active repo, I think the main advantage would be more robust issue/workitem tracking. DevOps has a much nicer agile/scrum backlog system that makes tracking which issues/items should be worked first and are currently being worked easier to see than the single issue list in GitHub and makes it easier for team efforts.

Note that GitHub also has various work-planning and -tracking features (in the `Projects` section). I have never used those a lot, though.

> GitHub seems pretty single-dev oriented, with collaboration and dividing up issues left to coordinate amongst the users... 

I disagree. GitHub is not single-dev oriented at all. There are plenty of tools and features for collaboration. I'd even say the primary purpose of GitHub is to enable collaborative work on open-source projects. 

However, GitHub is certainly not as enterprise-oriented as Azure. Historically, GitHub comes from the world of community-driven open-source projects, where you usually don't have one dev team hired by a single company, but a loosely coupled group of scattered developers, who don't necessarily follow one consistent development plan.
